In [1]:
import json

import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesRegressor, GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso, LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures
from tqdm.auto import tqdm
from xgboost import XGBRegressor


# === Load data ===
with open("data/nq_2024_11_07_12_14_naive/results/rag_evaluation_results_temp_940.json") as f1:
    rag_data = json.load(f1)
with open("data/nq_2024_11_07_12_14_naive/results/seper_results_temp_940.json") as f2:
    seper_data = json.load(f2)

# === Define models ===
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.01),
    "RandomForest": RandomForestRegressor(n_estimators=100, random_state=42),
    "ExtraTrees": ExtraTreesRegressor(n_estimators=100, random_state=42),
    "GradientBoosting": GradientBoostingRegressor(n_estimators=100, random_state=42),
    "XGBoost": XGBRegressor(n_estimators=100, random_state=42, tree_method='gpu_hist', predictor='gpu_predictor', verbosity=0),
    "Poly+LR": make_pipeline(PolynomialFeatures(degree=2, include_bias=False), LinearRegression()),
}

# === Clean & prepare per-metric data ===
seper_map = {item["id"]: item for item in seper_data}
all_metrics = [m for m in rag_data[0]["naive_metrics"].keys() if m != "PTrue"]
cleaned_data = {}
nan_records = []

for metric in all_metrics:
    rows = []
    for rag_item in rag_data:
        qid = rag_item["id"]
        if qid not in seper_map:
            continue
        seper_item = seper_map[qid]
        try:
            naive_value = rag_item["naive_metrics"][metric]
            rag_docs = rag_item["individual_doc_results"]
            seper_docs = seper_item["individual_doc_results"]

            for doc_idx, (rag_doc, seper_doc) in enumerate(zip(rag_docs, seper_docs)):
                doc_value = rag_doc["metrics"].get(metric)
                seper_reduction = seper_doc["utility"]["seper_reduction"]

                if not np.isfinite(naive_value) or not np.isfinite(doc_value) or not np.isfinite(seper_reduction):
                    nan_records.append({"metric": metric, "question_id": qid, "doc_index": doc_idx})
                    continue

                avg_val = (doc_value + naive_value) / 2
                diff = doc_value - naive_value
                ratio = doc_value / (naive_value + 1e-8)

                row = {
                    "question_id": qid,
                    "doc_index": doc_idx,
                    "naive": naive_value,
                    "doc": doc_value,
                    "diff": diff,
                    "ratio": ratio,
                    "avg": avg_val,
                    "diff_abs": abs(diff),
                    "naive_sq": naive_value ** 2,
                    "doc_sq": doc_value ** 2,
                    "doc_minus_avg": doc_value - avg_val,
                    "min_val": min(doc_value, naive_value),
                    "max_val": max(doc_value, naive_value),
                    "harmonic_mean": (2 * naive_value * doc_value) / (naive_value + doc_value + 1e-8),
                    "ratio_log": np.log1p(ratio),
                    "doc_normalized": doc_value / (avg_val + 1e-8),
                    "seper_reduction": seper_reduction,
                }

                # 过滤这行是否包含 nan
                if all(np.isfinite(v) for v in row.values() if isinstance(v, (int, float))):
                    rows.append(row)
                else:
                    nan_records.append({"metric": metric, "question_id": qid, "doc_index": doc_idx})

        except KeyError:
            continue

    if len(rows) >= 10:
        cleaned_data[metric] = pd.DataFrame(rows)

# === Training function ===
results = []
previews = {}

def run_regression(metric, model_name, model):
    df = cleaned_data[metric].copy()
    X = df.drop(columns=["question_id", "doc_index", "seper_reduction"])
    y = df["seper_reduction"]

    model.fit(X, y)
    y_pred = model.predict(X)

    result = {
        "metric": metric,
        "model": model_name,
        "r2_score": r2_score(y, y_pred),
        "mse": mean_squared_error(y, y_pred),
        "n_samples": len(df),
    }

    preview = df[["question_id", "doc_index"]].copy()
    preview["ground_truth"] = y
    preview["predicted"] = y_pred
    return result, preview.head(10)

# === Run all ===
for metric in tqdm(cleaned_data.keys(), desc="Metrics"):
    for model_name, model in tqdm(models.items(), leave=False, desc=f"{metric}"):
        res, preview = run_regression(metric, model_name, model)
        if res:
            results.append(res)
            previews[(metric, model_name)] = preview

# === Output summary ===
summary_df = pd.DataFrame(results).sort_values(by=["metric", "r2_score"], ascending=[True, False])
print("\n===== Summary of All Models per Metric =====")
print(summary_df.round(4))

/tmp/ipykernel_919230/2240006278.py:75: RuntimeWarning: invalid value encountered in log1p
  "ratio_log": np.log1p(ratio),

Metrics:   0%|          | 0/19 [00:00<?, ?it/s]

MaximumSequenceProbability:   0%|          | 0/8 [00:00<?, ?it/s]

/home/yijiexu/micromamba/envs/semantic_uncertainty/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.301e+01, tolerance: 5.250e-02
  model = cd_fast.enet_coordinate_descent(

Perplexity:   0%|          | 0/8 [00:00<?, ?it/s]

MeanTokenEntropy:   0%|          | 0/8 [00:00<?, ?it/s]

MonteCarloSequenceEntropy:   0%|          | 0/8 [00:00<?, ?it/s]

/home/yijiexu/micromamba/envs/semantic_uncertainty/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.896e+01, tolerance: 1.024e-02
  model = cd_fast.enet_coordinate_descent(

MonteCarloNormalizedSequenceEntropy:   0%|          | 0/8 [00:00<?, ?it/s]

RenyiNeg:   0%|          | 0/8 [00:00<?, ?it/s]

FisherRao:   0%|          | 0/8 [00:00<?, ?it/s]

SemanticEntropy:   0%|          | 0/8 [00:00<?, ?it/s]

CCP:   0%|          | 0/8 [00:00<?, ?it/s]

TokenSAR:   0%|          | 0/8 [00:00<?, ?it/s]

SentenceSAR:   0%|          | 0/8 [00:00<?, ?it/s]

SAR:   0%|          | 0/8 [00:00<?, ?it/s]

NumSemSets:   0%|          | 0/8 [00:00<?, ?it/s]

EigValLaplacian_NLI_score_entail:   0%|          | 0/8 [00:00<?, ?it/s]

DegMat_NLI_score_entail:   0%|          | 0/8 [00:00<?, ?it/s]

Eccentricity_NLI_score_entail:   0%|          | 0/8 [00:00<?, ?it/s]

LexicalSimilarity_rougeL:   0%|          | 0/8 [00:00<?, ?it/s]

KernelLanguageEntropy:   0%|          | 0/8 [00:00<?, ?it/s]

LUQ:   0%|          | 0/8 [00:00<?, ?it/s]

===== Summary of All Models per Metric =====
      metric             model  r2_score     mse  n_samples
68       CCP        ExtraTrees    0.1756  0.0872       4916
67       CCP      RandomForest    0.1436  0.0906       4916
70       CCP           XGBoost    0.0961  0.0956       4916
69       CCP  GradientBoosting    0.0478  0.1007       4916
71       CCP           Poly+LR    0.0045  0.1053       4916
..       ...               ...       ...     ...        ...
77  TokenSAR  GradientBoosting    0.1424  0.0910       4947
79  TokenSAR           Poly+LR    0.0075  0.1053       4947
72  TokenSAR  LinearRegression    0.0027  0.1059       4947
73  TokenSAR             Ridge    0.0025  0.1059       4947
74  TokenSAR             Lasso    0.0000  0.1061       4947

[152 rows x 5 columns]

In [2]:
summary_df

      metric             model  r2_score       mse  n_samples
68       CCP        ExtraTrees  0.175557  0.087195       4916
67       CCP      RandomForest  0.143559  0.090580       4916
70       CCP           XGBoost  0.096093  0.095600       4916
69       CCP  GradientBoosting  0.047797  0.100708       4916
71       CCP           Poly+LR  0.004507  0.105286       4916
..       ...               ...       ...       ...        ...
77  TokenSAR  GradientBoosting  0.142363  0.091025       4947
79  TokenSAR           Poly+LR  0.007527  0.105336       4947
72  TokenSAR  LinearRegression  0.002671  0.105851       4947
73  TokenSAR             Ridge  0.002464  0.105873       4947
74  TokenSAR             Lasso  0.000000  0.106134       4947

[152 rows x 5 columns]

In [3]:
# === 用于在 Jupyter 中展示每个模型+metric的 top 5 预测 vs 实际值 ===

from IPython.display import display, HTML

print("🔍 Showing top-5 predictions for each (metric, model) in ranked order:\n")

for _, row in summary_df.iterrows():
    metric = row["metric"]
    model = row["model"]

    key = (metric, model)
    if key not in previews:
        continue

    print(f"📌 Metric: {metric} | Model: {model}")
    print(f"R²: {row['r2_score']:.4f} | MSE: {row['mse']:.6f} | Samples: {int(row['n_samples'])}")

    preview_df = previews[key].copy()
    preview_df.columns = ["question_id", "doc_index", "ground_truth", "predicted"]
    display(HTML(preview_df.to_html(index=False)))

🔍 Showing top-5 predictions for each (metric, model) in ranked order:

📌 Metric: CCP | Model: ExtraTrees
R²: 0.1756 | MSE: 0.087195 | Samples: 4916

📌 Metric: CCP | Model: RandomForest
R²: 0.1436 | MSE: 0.090580 | Samples: 4916

📌 Metric: CCP | Model: XGBoost
R²: 0.0961 | MSE: 0.095600 | Samples: 4916

📌 Metric: CCP | Model: GradientBoosting
R²: 0.0478 | MSE: 0.100708 | Samples: 4916

📌 Metric: CCP | Model: Poly+LR
R²: 0.0045 | MSE: 0.105286 | Samples: 4916

📌 Metric: CCP | Model: LinearRegression
R²: 0.0014 | MSE: 0.105614 | Samples: 4916

📌 Metric: CCP | Model: Ridge
R²: 0.0001 | MSE: 0.105756 | Samples: 4916

📌 Metric: CCP | Model: Lasso
R²: 0.0000 | MSE: 0.105763 | Samples: 4916

📌 Metric: DegMat_NLI_score_entail | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: RandomForest
R²: 0.8574 | MSE: 0.015554 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: XGBoost
R²: 0.4983 | MSE: 0.054723 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: GradientBoosting
R²: 0.0880 | MSE: 0.099472 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: Poly+LR
R²: 0.0127 | MSE: 0.107692 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: LinearRegression
R²: 0.0077 | MSE: 0.108230 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: Ridge
R²: 0.0058 | MSE: 0.108439 | Samples: 9400

📌 Metric: DegMat_NLI_score_entail | Model: Lasso
R²: 0.0000 | MSE: 0.109075 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: RandomForest
R²: 0.8644 | MSE: 0.014793 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: XGBoost
R²: 0.4829 | MSE: 0.056398 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: GradientBoosting
R²: 0.1017 | MSE: 0.097987 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: Poly+LR
R²: 0.0122 | MSE: 0.107748 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: LinearRegression
R²: 0.0080 | MSE: 0.108198 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: Ridge
R²: 0.0080 | MSE: 0.108199 | Samples: 9400

📌 Metric: Eccentricity_NLI_score_entail | Model: Lasso
R²: 0.0058 | MSE: 0.108437 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: RandomForest
R²: 0.8605 | MSE: 0.015221 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: XGBoost
R²: 0.5053 | MSE: 0.053963 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: GradientBoosting
R²: 0.0998 | MSE: 0.098192 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: Poly+LR
R²: 0.0113 | MSE: 0.107843 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: LinearRegression
R²: 0.0065 | MSE: 0.108369 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: Ridge
R²: 0.0064 | MSE: 0.108377 | Samples: 9400

📌 Metric: EigValLaplacian_NLI_score_entail | Model: Lasso
R²: 0.0015 | MSE: 0.108909 | Samples: 9400

📌 Metric: FisherRao | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 4947

📌 Metric: FisherRao | Model: RandomForest
R²: 0.8533 | MSE: 0.015570 | Samples: 4947

📌 Metric: FisherRao | Model: XGBoost
R²: 0.6611 | MSE: 0.035969 | Samples: 4947

📌 Metric: FisherRao | Model: GradientBoosting
R²: 0.1245 | MSE: 0.092919 | Samples: 4947

📌 Metric: FisherRao | Model: Poly+LR
R²: 0.0055 | MSE: 0.105549 | Samples: 4947

📌 Metric: FisherRao | Model: LinearRegression
R²: 0.0032 | MSE: 0.105794 | Samples: 4947

📌 Metric: FisherRao | Model: Ridge
R²: 0.0000 | MSE: 0.106132 | Samples: 4947

📌 Metric: FisherRao | Model: Lasso
R²: 0.0000 | MSE: 0.106134 | Samples: 4947

📌 Metric: KernelLanguageEntropy | Model: ExtraTrees
R²: 0.9899 | MSE: 0.001105 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: RandomForest
R²: 0.8520 | MSE: 0.016139 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: XGBoost
R²: 0.4966 | MSE: 0.054907 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: GradientBoosting
R²: 0.1001 | MSE: 0.098159 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: Poly+LR
R²: 0.0117 | MSE: 0.107801 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: LinearRegression
R²: 0.0027 | MSE: 0.108782 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: Ridge
R²: 0.0017 | MSE: 0.108893 | Samples: 9400

📌 Metric: KernelLanguageEntropy | Model: Lasso
R²: 0.0000 | MSE: 0.109075 | Samples: 9400

📌 Metric: LUQ | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: LUQ | Model: RandomForest
R²: 0.8576 | MSE: 0.015538 | Samples: 9400

📌 Metric: LUQ | Model: XGBoost
R²: 0.5157 | MSE: 0.052830 | Samples: 9400

📌 Metric: LUQ | Model: GradientBoosting
R²: 0.0971 | MSE: 0.098488 | Samples: 9400

📌 Metric: LUQ | Model: Poly+LR
R²: 0.0121 | MSE: 0.107757 | Samples: 9400

📌 Metric: LUQ | Model: LinearRegression
R²: 0.0080 | MSE: 0.108204 | Samples: 9400

📌 Metric: LUQ | Model: Ridge
R²: 0.0078 | MSE: 0.108221 | Samples: 9400

📌 Metric: LUQ | Model: Lasso
R²: 0.0020 | MSE: 0.108860 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: RandomForest
R²: 0.8603 | MSE: 0.015235 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: XGBoost
R²: 0.5279 | MSE: 0.051496 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: GradientBoosting
R²: 0.1006 | MSE: 0.098099 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: Poly+LR
R²: 0.0107 | MSE: 0.107912 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: LinearRegression
R²: 0.0073 | MSE: 0.108277 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: Ridge
R²: 0.0040 | MSE: 0.108639 | Samples: 9400

📌 Metric: LexicalSimilarity_rougeL | Model: Lasso
R²: 0.0000 | MSE: 0.109075 | Samples: 9400

📌 Metric: MaximumSequenceProbability | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: RandomForest
R²: 0.8578 | MSE: 0.015097 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: XGBoost
R²: 0.6890 | MSE: 0.033007 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: GradientBoosting
R²: 0.1470 | MSE: 0.090529 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: Poly+LR
R²: 0.0129 | MSE: 0.104765 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: LinearRegression
R²: 0.0066 | MSE: 0.105436 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: Ridge
R²: 0.0055 | MSE: 0.105554 | Samples: 4947

📌 Metric: MaximumSequenceProbability | Model: Lasso
R²: 0.0036 | MSE: 0.105750 | Samples: 4947

📌 Metric: MeanTokenEntropy | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: RandomForest
R²: 0.8508 | MSE: 0.016274 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: XGBoost
R²: 0.4874 | MSE: 0.055916 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: GradientBoosting
R²: 0.0819 | MSE: 0.100141 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: Poly+LR
R²: 0.0089 | MSE: 0.108103 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: LinearRegression
R²: 0.0051 | MSE: 0.108517 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: Ridge
R²: 0.0048 | MSE: 0.108552 | Samples: 9400

📌 Metric: MeanTokenEntropy | Model: Lasso
R²: 0.0000 | MSE: 0.109075 | Samples: 9400

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: XGBoost
R²: 0.9838 | MSE: 0.001783 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: RandomForest
R²: 0.8702 | MSE: 0.014281 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: GradientBoosting
R²: 0.4788 | MSE: 0.057339 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: Poly+LR
R²: 0.0707 | MSE: 0.102235 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: LinearRegression
R²: 0.0420 | MSE: 0.105393 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: Ridge
R²: 0.0326 | MSE: 0.106436 | Samples: 931

📌 Metric: MonteCarloNormalizedSequenceEntropy | Model: Lasso
R²: 0.0179 | MSE: 0.108049 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: XGBoost
R²: 0.9766 | MSE: 0.002573 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: RandomForest
R²: 0.8698 | MSE: 0.014320 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: GradientBoosting
R²: 0.4472 | MSE: 0.060815 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: Poly+LR
R²: 0.0712 | MSE: 0.102187 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: LinearRegression
R²: 0.0528 | MSE: 0.104214 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: Ridge
R²: 0.0409 | MSE: 0.105515 | Samples: 931

📌 Metric: MonteCarloSequenceEntropy | Model: Lasso
R²: 0.0408 | MSE: 0.105534 | Samples: 931

📌 Metric: NumSemSets | Model: Poly+LR
R²: 0.0031 | MSE: 0.108735 | Samples: 9400

📌 Metric: NumSemSets | Model: ExtraTrees
R²: 0.0031 | MSE: 0.108735 | Samples: 9400

📌 Metric: NumSemSets | Model: XGBoost
R²: 0.0031 | MSE: 0.108735 | Samples: 9400

📌 Metric: NumSemSets | Model: GradientBoosting
R²: 0.0031 | MSE: 0.108735 | Samples: 9400

📌 Metric: NumSemSets | Model: RandomForest
R²: 0.0031 | MSE: 0.108740 | Samples: 9400

📌 Metric: NumSemSets | Model: LinearRegression
R²: 0.0012 | MSE: 0.108939 | Samples: 9400

📌 Metric: NumSemSets | Model: Ridge
R²: 0.0011 | MSE: 0.108954 | Samples: 9400

📌 Metric: NumSemSets | Model: Lasso
R²: 0.0005 | MSE: 0.109025 | Samples: 9400

📌 Metric: Perplexity | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 4947

📌 Metric: Perplexity | Model: RandomForest
R²: 0.8571 | MSE: 0.015169 | Samples: 4947

📌 Metric: Perplexity | Model: XGBoost
R²: 0.6809 | MSE: 0.033870 | Samples: 4947

📌 Metric: Perplexity | Model: GradientBoosting
R²: 0.1398 | MSE: 0.091298 | Samples: 4947

📌 Metric: Perplexity | Model: Poly+LR
R²: 0.0072 | MSE: 0.105370 | Samples: 4947

📌 Metric: Perplexity | Model: LinearRegression
R²: 0.0024 | MSE: 0.105883 | Samples: 4947

📌 Metric: Perplexity | Model: Ridge
R²: 0.0022 | MSE: 0.105899 | Samples: 4947

📌 Metric: Perplexity | Model: Lasso
R²: 0.0000 | MSE: 0.106134 | Samples: 4947

📌 Metric: RenyiNeg | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 4947

📌 Metric: RenyiNeg | Model: RandomForest
R²: 0.8523 | MSE: 0.015674 | Samples: 4947

📌 Metric: RenyiNeg | Model: XGBoost
R²: 0.6883 | MSE: 0.033079 | Samples: 4947

📌 Metric: RenyiNeg | Model: GradientBoosting
R²: 0.1311 | MSE: 0.092223 | Samples: 4947

📌 Metric: RenyiNeg | Model: Poly+LR
R²: 0.0075 | MSE: 0.105339 | Samples: 4947

📌 Metric: RenyiNeg | Model: LinearRegression
R²: 0.0041 | MSE: 0.105704 | Samples: 4947

📌 Metric: RenyiNeg | Model: Ridge
R²: 0.0024 | MSE: 0.105884 | Samples: 4947

📌 Metric: RenyiNeg | Model: Lasso
R²: 0.0022 | MSE: 0.105900 | Samples: 4947

📌 Metric: SAR | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 9400

📌 Metric: SAR | Model: RandomForest
R²: 0.8550 | MSE: 0.015811 | Samples: 9400

📌 Metric: SAR | Model: XGBoost
R²: 0.5044 | MSE: 0.054061 | Samples: 9400

📌 Metric: SAR | Model: GradientBoosting
R²: 0.0881 | MSE: 0.099467 | Samples: 9400

📌 Metric: SAR | Model: Poly+LR
R²: 0.0165 | MSE: 0.107275 | Samples: 9400

📌 Metric: SAR | Model: LinearRegression
R²: 0.0147 | MSE: 0.107474 | Samples: 9400

📌 Metric: SAR | Model: Ridge
R²: 0.0128 | MSE: 0.107680 | Samples: 9400

📌 Metric: SAR | Model: Lasso
R²: 0.0119 | MSE: 0.107776 | Samples: 9400

📌 Metric: SemanticEntropy | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 2243

📌 Metric: SemanticEntropy | Model: XGBoost
R²: 0.8627 | MSE: 0.014433 | Samples: 2243

📌 Metric: SemanticEntropy | Model: RandomForest
R²: 0.8541 | MSE: 0.015339 | Samples: 2243

📌 Metric: SemanticEntropy | Model: GradientBoosting
R²: 0.2308 | MSE: 0.080859 | Samples: 2243

📌 Metric: SemanticEntropy | Model: Poly+LR
R²: 0.0176 | MSE: 0.103269 | Samples: 2243

📌 Metric: SemanticEntropy | Model: LinearRegression
R²: 0.0065 | MSE: 0.104433 | Samples: 2243

📌 Metric: SemanticEntropy | Model: Ridge
R²: 0.0062 | MSE: 0.104468 | Samples: 2243

📌 Metric: SemanticEntropy | Model: Lasso
R²: 0.0060 | MSE: 0.104485 | Samples: 2243

📌 Metric: SentenceSAR | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 8981

📌 Metric: SentenceSAR | Model: RandomForest
R²: 0.8637 | MSE: 0.015011 | Samples: 8981

📌 Metric: SentenceSAR | Model: XGBoost
R²: 0.5233 | MSE: 0.052495 | Samples: 8981

📌 Metric: SentenceSAR | Model: GradientBoosting
R²: 0.0971 | MSE: 0.099435 | Samples: 8981

📌 Metric: SentenceSAR | Model: Poly+LR
R²: 0.0072 | MSE: 0.109338 | Samples: 8981

📌 Metric: SentenceSAR | Model: LinearRegression
R²: 0.0023 | MSE: 0.109875 | Samples: 8981

📌 Metric: SentenceSAR | Model: Ridge
R²: 0.0023 | MSE: 0.109875 | Samples: 8981

📌 Metric: SentenceSAR | Model: Lasso
R²: 0.0020 | MSE: 0.109914 | Samples: 8981

📌 Metric: TokenSAR | Model: ExtraTrees
R²: 1.0000 | MSE: 0.000000 | Samples: 4947

📌 Metric: TokenSAR | Model: RandomForest
R²: 0.8561 | MSE: 0.015268 | Samples: 4947

📌 Metric: TokenSAR | Model: XGBoost
R²: 0.6833 | MSE: 0.033610 | Samples: 4947

📌 Metric: TokenSAR | Model: GradientBoosting
R²: 0.1424 | MSE: 0.091025 | Samples: 4947

📌 Metric: TokenSAR | Model: Poly+LR
R²: 0.0075 | MSE: 0.105336 | Samples: 4947

📌 Metric: TokenSAR | Model: LinearRegression
R²: 0.0027 | MSE: 0.105851 | Samples: 4947

📌 Metric: TokenSAR | Model: Ridge
R²: 0.0025 | MSE: 0.105873 | Samples: 4947

📌 Metric: TokenSAR | Model: Lasso
R²: 0.0000 | MSE: 0.106134 | Samples: 4947

In [3]:
# === Sample prediction output ===
print("\n===== Sample Predictions =====")
for (metric, model_name), preview in list(previews.items())[:5]:
    print(f"\n--- {metric} | {model_name} ---")
    print(preview.to_string(index=False))

===== Sample Predictions =====

--- MaximumSequenceProbability | LinearRegression ---
question_id  doc_index  seper_reduction  predicted
  test_2619          0         0.990489   0.086926
  test_2619          1         0.004199   0.119428
  test_2619          2         0.990489   0.090348
  test_2619          3         0.219955   0.079978
  test_2619          4         0.002516   0.098800

--- MaximumSequenceProbability | Ridge ---
question_id  doc_index  seper_reduction  predicted
  test_2619          0         0.990489   0.086926
  test_2619          1         0.004199   0.119429
  test_2619          2         0.990489   0.090348
  test_2619          3         0.219955   0.079979
  test_2619          4         0.002516   0.098800

--- MaximumSequenceProbability | Lasso ---
question_id  doc_index  seper_reduction  predicted
  test_2619          0         0.990489   0.089044
  test_2619          1         0.004199   0.123088
  test_2619          2         0.990489   0.092628
  test_2619          3         0.219955   0.081767
  test_2619          4         0.002516   0.101481

--- MaximumSequenceProbability | RandomForest ---
question_id  doc_index  seper_reduction  predicted
  test_2619          0         0.990489   0.700214
  test_2619          1         0.004199   0.012001
  test_2619          2         0.990489   0.666430
  test_2619          3         0.219955   0.238120
  test_2619          4         0.002516   0.076910

--- MaximumSequenceProbability | ExtraTrees ---
question_id  doc_index  seper_reduction  predicted
  test_2619          0         0.990489   0.990489
  test_2619          1         0.004199   0.004199
  test_2619          2         0.990489   0.990489
  test_2619          3         0.219955   0.219955
  test_2619          4         0.002516   0.002516